<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdManager.DataAccess\AdManager.DataAccess.csproj" />
    <ProjectReference Include="..\AdManager.Interface\AdManager.Interface.csproj" />
    <ProjectReference Include="..\AdManager.Model\AdManager.Model.csproj" />
  </ItemGroup>
</Project>
